name: Deploy dist
on: [push,workflow_dispatch] #event
jobs: 
    greet:
        runs-on: ubuntu-latest
        steps: 
            - name: "Get Code"
              run: |
                echo "Cloning Repo"
                echo ${{toJson(github) }} 
                echo git clone https://github.com/${{ github.repository }}.git
